backlog=[
  {
    "project_id": 1,
    "id": 1001,
    "name": "Project initialization & repo setup",
    "description": "Create repository structure, branch strategy, README, CODEOWNERS, and initial license.",
    "issue_type": "task",
    "status": "todo",
    "priority": "high",
    "assignee": None,
    "story_points": 3,
    "sprint": None,
    "tags": ["devops","setup","documentation"]
  },{
    "project_id": 1,
    "id": 2001,
    "name": "Login fails with valid credentials",
    "description": "Users cannot log in even with correct username and password.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "high",
    "severity": "critical",
    "assignee": None,
    "story_points": 5,
    "sprint": None,
    "tags": ["auth", "login", "production"]
  },
  {
    "project_id": 1,
    "id": 2002,
    "name": "Password reset email not sent",
    "description": "Password reset emails are not delivered to users.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "high",
    "severity": "major",
    "assignee": None,
    "story_points": 3,
    "sprint": None,
    "tags": ["auth", "email"]
  },
  {
    "project_id": 1,
    "id": 2003,
    "name": "User session expires too early",
    "description": "User sessions expire within minutes instead of configured duration.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "medium",
    "severity": "major",
    "assignee": None,
    "story_points": 3,
    "sprint": None,
    "tags": ["session", "security"]
  },
  {
    "project_id": 1,
    "id": 2004,
    "name": "Project list not loading",
    "description": "Projects page shows blank screen for some users.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "high",
    "severity": "critical",
    "assignee": None,
    "story_points": 5,
    "sprint": None,
    "tags": ["ui", "project"]
  },
  {
    "project_id": 1,
    "id": 2005,
    "name": "Incorrect role permissions applied",
    "description": "Users can access features outside their assigned role.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "high",
    "severity": "critical",
    "assignee": None,
    "story_points": 5,
    "sprint": None,
    "tags": ["security", "rbac"]
  },
  {
    "project_id": 1,
    "id": 2006,
    "name": "Sprint board drag-and-drop not working",
    "description": "Tasks cannot be moved between columns on sprint board.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "medium",
    "severity": "major",
    "assignee": None,
    "story_points": 3,
    "sprint": None,
    "tags": ["board", "ui"]
  },
  {
    "project_id": 1,
    "id": 2007,
    "name": "Comments not saved on issues",
    "description": "User comments disappear after page refresh.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "medium",
    "severity": "major",
    "assignee": None,
    "story_points": 2,
    "sprint": None,
    "tags": ["comments", "backend"]
  },
  {
    "project_id": 1,
    "id": 2008,
    "name": "Notification badge count incorrect",
    "description": "Unread notification count does not match actual notifications.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "low",
    "severity": "minor",
    "assignee": None,
    "story_points": 1,
    "sprint": None,
    "tags": ["notification", "ui"]
  },
  {
    "project_id": 1,
    "id": 2009,
    "name": "Meeting audio not connecting",
    "description": "Users cannot hear audio after joining meetings.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "high",
    "severity": "critical",
    "assignee": None,
    "story_points": 8,
    "sprint": None,
    "tags": ["meeting", "audio"]
  },
  {
    "project_id": 1,
    "id": 2010,
    "name": "Chat messages delivered with delay",
    "description": "Real-time chat messages are delayed by several seconds.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "medium",
    "severity": "major",
    "assignee": None,
    "story_points": 3,
    "sprint": None,
    "tags": ["chat", "realtime"]
  },
  {
    "project_id": 1,
    "id": 2011,
    "name": "File upload fails for large files",
    "description": "Uploading files larger than 10MB fails without error message.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "medium",
    "severity": "major",
    "assignee": None,
    "story_points": 3,
    "sprint": None,
    "tags": ["upload", "backend"]
  },
  {
    "project_id": 1,
    "id": 2012,
    "name": "Search returns incomplete results",
    "description": "Search does not return all matching records.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "medium",
    "severity": "minor",
    "assignee": None,
    "story_points": 2,
    "sprint": None,
    "tags": ["search"]
  },
  {
    "project_id": 1,
    "id": 2013,
    "name": "API returns 500 error intermittently",
    "description": "Random internal server errors observed in production.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "high",
    "severity": "critical",
    "assignee": None,
    "story_points": 8,
    "sprint": None,
    "tags": ["api", "backend"]
  },
  {
    "project_id": 1,
    "id": 2014,
    "name": "Timezone mismatch in reports",
    "description": "Report timestamps are displayed in incorrect timezone.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "low",
    "severity": "minor",
    "assignee": None,
    "story_points": 1,
    "sprint": None,
    "tags": ["report", "timezone"]
  },
  {
    "project_id": 1,
    "id": 2015,
    "name": "Duplicate notifications sent",
    "description": "Users receive same notification multiple times.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "low",
    "severity": "minor",
    "assignee": None,
    "story_points": 2,
    "sprint": None,
    "tags": ["notification"]
  },
  {
    "project_id": 1,
    "id": 2016,
    "name": "Sprint velocity calculated incorrectly",
    "description": "Velocity does not match completed story points.",
    "issue_type": "bug",
    "status": "todo",
    "priority": "medium",
    "severity": "major",
    "assignee": None,
    "story_points": 3,
    "sprint": None,
    "tags": ["agile", "metrics"]
  }
  ,
  {
    "project_id": 1,
    "id": 1010,
    "name": "Core API: CRUD for primary resource",
    "description": "Implement REST/GraphQL endpoints for main domain entity with validation and error handling.",
    "issue_type": "story",
    "status": "todo",
    "priority": "high",
    "assignee": None,
    "story_points": 13,
    "sprint": None,
    "tags": ["backend","api","mvp"]
  },
  {
    "project_id": 1,
    "id": 1011,
    "name": "Logging & monitoring baseline",
    "description": "Add structured logging, request tracing, basic metrics and integrate with monitoring dashboard.",
    "issue_type": "task",
    "status": "todo",
    "priority": "medium",
    "assignee": None,
    "story_points": 5,
    "sprint": None,
    "tags": ["observability","ops"]
  },
  {
    "project_id": 1,
    "id": 1012,
    "name": "Automated tests: unit & integration",
    "description": "Create test framework and add unit tests for core modules and integration tests for API.",
    "issue_type": "task",
    "status": "todo",
    "priority": "high",
    "assignee": None,
    "story_points": 8,
    "sprint": None,
    "tags": ["qa","testing"]
  },
  {
    "project_id": 1,
    "id": 1013,
    "name": "End-to-end (E2E) smoke tests",
    "description": "Implement simple E2E tests to verify critical user flows (login, create resource, logout).",
    "issue_type": "task",
    "status": "todo",
    "priority": "medium",
    "assignee": None,
    "story_points": 5,
    "sprint": None,
    "tags": ["qa","e2e"]
  },
  {
    "project_id": 1,
    "id": 1014,
    "name": "Security review & dependency audit",
    "description": "Run SCA, fix critical vulnerabilities, add dependency update policy and secrets management plan.",
    "issue_type": "task",
    "status": "todo",
    "priority": "high",
    "assignee": None,
    "story_points": 5,
    "sprint": None,
    "tags": ["security","dependencies"]
  },
  {
    "project_id": 1,
    "id": 1015,
    "name": "Deployment: staging environment",
    "description": "Deploy initial build to staging environment with automated deploy pipeline and rollback strategy.",
    "issue_type": "task",
    "status": "todo",
    "priority": "high",
    "assignee": None,
    "story_points": 8,
    "sprint": None,
    "tags": ["devops","deployment"]
  },
  {
    "project_id": 1,
    "id": 1016,
    "name": "Performance baseline & profiling plan",
    "description": "Establish performance goals, add basic load tests and profiling guidelines for future work.",
    "issue_type": "task",
    "status": "todo",
    "priority": "low",
    "assignee": None,
    "story_points": 3,
    "sprint": None,
    "tags": ["performance","testing"]
  },
  {
    "project_id": 1,
    "id": 1017,
    "name": "Data protection & backup plan",
    "description": "Define backup/retention policy, restore playbook, and data encryption-at-rest/in-transit requirements.",
    "issue_type": "task",
    "status": "todo",
    "priority": "medium",
    "assignee": None,
    "story_points": 3,
    "sprint": None,
    "tags": ["ops","security","compliance"]
  },
  {
    "project_id": 1,
    "id": 1018,
    "name": "User documentation & API docs",
    "description": "Create user-facing docs, API reference (OpenAPI/Swagger) and developer docs for contributors.",
    "issue_type": "task",
    "status": "todo",
    "priority": "medium",
    "assignee": None,
    "story_points": 5,
    "sprint": None,
    "tags": ["docs","api"]
  },
  {
    "project_id": 1,
    "id": 1019,
    "name": "Legal & compliance checklist",
    "description": "Collect requirements for privacy, licensing, third-party terms and confirm any regulatory needs.",
    "issue_type": "task",
    "status": "todo",
    "priority": "low",
    "assignee": None,
    "story_points": 2,
    "sprint": None,
    "tags": ["legal","compliance"]
  },
  {
    "project_id": 1,
    "id": 1020,
    "name": "Backlog grooming & roadmap planning",
    "description": "Run initial grooming session, prioritize backlog, and produce 3-month roadmap with milestones.",
    "issue_type": "task",
    "status": "todo",
    "priority": "high",
    "assignee": None,
    "story_points": 3,
    "sprint": None,
    "tags": ["process","planning"]
  }
]


